plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.flow'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven{url 'https://jitpack.io'}
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'

    //WebFlux
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // AOP
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    //Security
    implementation 'org.springframework.security:spring-security-core:6.3.0'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
    implementation 'io.jsonwebtoken:jjwt-impl:0.12.3'
    implementation 'io.jsonwebtoken:jjwt-jackson:0.12.3'

    //DB
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    //Mapper
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    //university
    implementation 'com.github.in-seo:univcert:master-SNAPSHOT'

    // P6Spy
    // implementation 'p6spy:p6spy:3.9.1'
    // implementation 'com.github.gavlyukovskiy:datasource-decorator-spring-boot-autoconfigure:1.9.0'
    // 출처: https://curiousjinan.tistory.com/entry/spring-boot-3-p6spy-jpa-logging [오늘도 개발중입니다:티스토리]

    implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:1.9.0'
    // 출처: https://curiousjinan.tistory.com/entry/spring-boot-3-p6spy-jpa-logging [오늘도 개발중입니다:티스토리]

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
