spring:
  application:
    name: flow-main
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Hibernate DDL (none, validate, update, create-drop)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${JWT_SECRET}
    access:
      expiration: ${ACCESS_EXPIRATION}
    refresh:
      expiration: ${REFRESH_EXPIRATION}
user:
  profile:
    url: ${PROFILE_URL}
  verify:
    key: ${UNIV_API_KEY}
file:
  upload:
    url: ${UPLOAD_URL}
    path: ${UPLOAD_PATH}